### ISSUE TITLE
Not compatible with storybook 6

### ISSUE THREAD

**Issue by adambullmer** [mattrothenberg/vue-storybook#26]
When upgrading an existing vue storybook project to storybook >=6.0.0, the following error is returned in the UI:

```
Unexpected default export without title: undefined
Error: Unexpected default export without title: undefined
    at http://localhost:8080/vendors~main.d193a683a2dcb6796807.bundle.js:10575:15
    at Array.forEach (<anonymous>)
    at http://localhost:8080/vendors~main.d193a683a2dcb6796807.bundle.js:10568:11
    at ConfigApi.configure (http://localhost:8080/vendors~main.d193a683a2dcb6796807.bundle.js:7619:7)
    at Object.configure (http://localhost:8080/vendors~main.d193a683a2dcb6796807.bundle.js:10716:17)
    at configure (http://localhost:8080/vendors~main.d193a683a2dcb6796807.bundle.js:12296:24)
    at Object.<anonymous> (http://localhost:8080/main.d193a683a2dcb6796807.bundle.js:15102:36)
    at Object../.storybook/generated-stories-entry.js (http://localhost:8080/main.d193a683a2dcb6796807.bundle.js:15103:30)
    at __webpack_require__ (http://localhost:8080/runtime~main.d193a683a2dcb6796807.bundle.js:849:30)
    at fn (http://localhost:8080/runtime~main.d193a683a2dcb6796807.bundle.js:151:20)
```

I believe storybook 6 requires that story files follow the SFC spec:
```js
import { action } from "@storybook/addon-actions";
import { linkTo } from "@storybook/addon-links";

import MyButton from "../components/MyButton.vue";

export default {
  component: MyButton,
  title: "Button"
};

export const withText = () => ({
  components: { MyButton },
  template: '<my-button @click="action">Hello Button</my-button>',
  methods: { action: action("clicked") }
});
```

Also, with the deprecation of config.js, I believe the configure and loadStories hooks have been lost, which may be necessary for this package to work properly.

**EDIT**
Errors will go away be defining a `title` attribute on the exported Vue component. In my case I am using the Class syntax from typescript so I had to do:

```vue
<script lang="ts">
import { Vue, Component } from "vue-property-decorator";

@Component
export default class ComponentStory extends Vue {
  public static title = "My Component";
}
```

While this does suppress the errors, these stories do not get loaded into the manager, which I think is related to the config.js storyloader from before.

**Comment by mattrothenberg** [comment]
Hi @adambullmer, this project hasn't been updated in nearly a year, so this error stands to reason.

PRs are totally welcome to make the project compatible with Storybook 6!
